apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: auth
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: auth
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: auth
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
          image: elza1428/test:latest
          name: auth
          ports:
            - containerPort: 80
          resources: {}
          volumeMounts:
            - mountPath: /app/appSettings.json
              subPath: appSettings.json
              name: auth-claim0
      restartPolicy: Always
      volumes:
        - name: auth-claim0
          persistentVolumeClaim:
            claimName: auth-claim0
status: {}
