apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: clientapp
  name: clientapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: clientapp
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: clientapp
    spec:
      containers:
        - image: elza1428/test-client:latest
          name: clientapp
          ports:
            - containerPort: 4200
            - containerPort: 49153
          resources: {}
          volumeMounts:
            - mountPath: /app
              name: clientapp-claim0
      restartPolicy: Always
      volumes:
        - name: clientapp-claim0
          persistentVolumeClaim:
            claimName: clientapp-claim0
status: {}
